### ISSUE TITLE
data

### ISSUE THREAD

**Issue by 54woshihangkongbing54** [joshua-wx/PyHail#5]
Hello, I would like to ask how to get the data in the code?

**Comment by joshua-wx** [comment]
Sorry, can you elaborate further on your problem?

**Comment by 54woshihangkongbing54** [comment]
hello!
Thank you for your reply,
I want to know what is the data in Python_hail\PyHail-master\notebooks\generate_hail_grids.ipynb, and how to make it.

&nbsp;Looking forward to your reply, Thank you!

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "joshua-wx/PyHail"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 上午8:53
收件人:&nbsp;"joshua-wx/PyHail"<PyHail@noreply.github.com&gt;;
抄送:&nbsp;"rr"<1076083241@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [joshua-wx/PyHail] data (#5)





 
Sorry, can you elaborate further on your problem?

**Comment by joshua-wx** [comment]
You'll require a weather radar volume that's compatible with PyART to use this script. For the HSDA/HCA, you'll also need a dual pol radar specifically.

**Comment by joshua-wx** [comment]
I can include a sample volume if that's helpful

**Comment by 54woshihangkongbing54** [comment]
Thank you for your reply,
I would like to ask how to download the raw data and how to make it, for example ('/g/data/kl02/jss548/hail-research/snding_data/YBBN_20141127_00.nc' and  '/g/data1a/kl02/jss548/hail-research/srtm/srtm_67_18_Brisbane/srtm_67_18.tif'  )  I don't understand what data is srtm_67_18.tif, Can you share your data for me?

Looking forward to your reply, Thank you!

**Comment by joshua-wx** [comment]
Ah ok - that's a very good point.
I'm working to update this example and provide a new dataset in the repo. Should have this done within a week.

Cheers,
Joshua

**Comment by 54woshihangkongbing54** [comment]
Thanks for sharing

**Comment by joshua-wx** [comment]
Hi, I've updated the repo with a standalone example. Hopefully this is helpful for you.

Cheers,
Joshua

**Comment by 54woshihangkongbing54** [comment]
Thank you very much for your help.
