### ISSUE TITLE
spatial plot of POSH

### ISSUE THREAD

**Issue by MohitDahliya** [joshua-wx/pyhail#8]
If we are calculating POSH to calculaTE MESH, then why can't we plot POSH as well ?

**Comment by joshua-wx** [comment]
POSH is also returned in the dictionary of new radar fields from the MESH functions - you can easily plot it up from there.
Also, POSH isn't calculated from MESH, it's calculated from SHI and WT
https://github.com/joshua-wx/pyhail/blob/07d57b1e5e2faa8251a202003286a4fc491d69b1/src/pyhail/mesh_ppi.py#L214

**Comment by MohitDahliya** [comment]
Yeah, got it... I was able to plot it..
